### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Angelo-Funelas** [Angelo-Funelas/panner.js#2]
- [x] Panning quickly near border stops panning and sometimes triggers clock
- [ ] Tapping on trackpad does trigger click
- [x] Standardize handling of options
- [x] Allow option to pan target outside image but inside container
